"""initial schema

Revision ID: 06d550bb635b
Revises: 
Create Date: 2025-11-19 22:39:54.550371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d550bb635b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('base_asset', sa.String(), nullable=True),
    sa.Column('quote_asset', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stacktrace', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('starting_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('base_currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('strategy_config_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('initial_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('final_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('benchmark_id', 'date')
    )
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timeframe', 'timestamp')
    )
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starting_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ending_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('deposits_withdrawals', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('num_winning_trades', sa.Integer(), nullable=True),
    sa.Column('num_losing_trades', sa.Integer(), nullable=True),
    sa.Column('max_intraday_drawdown', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('day_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'date')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('strategy_config_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('size', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('exchange_order_id', sa.String(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('strategy_config_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('strategy_config_id', sa.Integer(), nullable=True),
    sa.Column('entry_order_id', sa.Integer(), nullable=False),
    sa.Column('exit_order_id', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('realized_pnl_pct', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['entry_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['exit_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('signals')
    op.drop_table('risk_events')
    op.drop_table('orders')
    op.drop_table('daily_snapshots')
    op.drop_table('candles')
    op.drop_table('benchmark_snapshots')
    op.drop_table('backtest_runs')
    op.drop_table('strategy_configs')
    op.drop_table('portfolios')
    op.drop_table('errors')
    op.drop_table('benchmarks')
    op.drop_table('assets')
    # ### end Alembic commands ###
