"""added analytics column to trade model

Revision ID: 4463fcb6dc74
Revises: 06d550bb635b
Create Date: 2025-12-09 09:40:01.262530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4463fcb6dc74'
down_revision: Union[str, Sequence[str], None] = '06d550bb635b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('analytics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'analytics')
    # ### end Alembic commands ###
